import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import 'mapbox-gl/dist/mapbox-gl.css'

import Logland from '@/pages/login_landing'
import Merch from '@/pages/merchant_log'
import MerchSetup from '@/pages/merchant_setup_satu'
import MerchSetup2 from '@/pages/merchant_setup_dua'
import MerchantSetup3 from './merchant_setup_tiga'
import MerchHome from '@/components/merchant_homescreen'
import DriverSet1 from '@/pages/driver_setup_satu'
import DriverLand from './driver_landing'
import Menu_Page from './menu_page'
import MerchantHomescreen from './merchant_homescreen'
import Supplies from './supplies'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
    <>
      <Head>
        {/* <title>Create Capacitor App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* <Menu_Page/> */}
      {/* <MerchantHomescreen/> */}
      {/* <Supplies/> */}
      {/* <DriverLand/> */}
      {/* <MerchSetup/> */}
      <MerchantSetup3/>
      {/* <MerchHome/> */}
      {/* <Logland/> */}
      {/* <Merch/> */}
    </>
  )
}
